# å…¨å±€é…ç½®
mode: rule                                            # è¿è¡Œæ¨¡å¼rule/global/direct,åˆ†æµ/å…¨å±€/ç›´è¿
log-level: info                                       # æ—¥å¿—çº§åˆ«silent/error/warning/info/debug
port: 2080                                            # http(s) ä»£ç†ç«¯å£
socks-port: 2081                                      # socks4/4a/5 ä»£ç†ç«¯å£
mixed-port: 2082                                      # æ··åˆç«¯å£ åŒæ—¶æ”¯æŒ HTTP(S) å’Œ SOCKS5 åè®®
redir-port: 2083                                      # redirect é€æ˜ä»£ç†ç«¯å£,ä»…èƒ½ä»£ç† TCP æµé‡
tproxy-port: 2084                                     # tproxy é€æ˜ä»£ç†ç«¯å£,å¯ä»£ç† TCP ä¸ UDP æµé‡
allow-lan: true                                       # å…è®¸å±€åŸŸç½‘è¿æ¥ false / true
ipv6: true                                            # IPv6 æ˜¯å¦å…è®¸å†…æ ¸æ¥å— IPv6 æµé‡
tcp-concurrent: false                                 # TCP å¹¶å‘,å¦‚æœåŸŸåè§£æç»“æœå¯¹åº”å¤šä¸ªIP,å¹¶å‘è¯·æ±‚æ‰€æœ‰IP,é€‰æ‹©æ¡æ‰‹æœ€å¿«çš„IPè¿›è¡Œé€šè®¯
disable-keep-alive: false                             # ç¦ç”¨ TCP Keep Alive, åœ¨ Android é»˜è®¤ä¸º true
keep-alive-interval: 15                               # TCP Keep AliveåŒ…çš„é—´éš”,å‡å°‘ç§»åŠ¨è®¾å¤‡è€—ç”µé—®é¢˜,é»˜è®¤15ç§’
keep-alive-idle: 300                                  # TCP Keep Aliveç©ºé—²è¶…æ—¶,é»˜è®¤3600ç§’
unified-delay: true                                   # ç»Ÿä¸€å»¶è¿Ÿ
find-process-mode: strict                             # è¿›ç¨‹æ¨¡å¼off/strict/always

# GEOIPåœ°å€åº“é…ç½®
geodata-mode: true                                    # GEOIPæ•°æ®æ¨¡å¼,æ›´æ”¹geoipä½¿ç”¨æ–‡ä»¶,mmdbæˆ–è€…dat,å¯é€‰,trueä¸ºdat
geodata-loader: standard                              # GEO æ–‡ä»¶åŠ è½½æ¨¡å¼ standard / memconservative æ ‡å‡† / å°å†…å­˜(é»˜è®¤å€¼)
geo-auto-update: true                                 # è‡ªåŠ¨æ›´æ–° GEO æ˜¯å¦å¯ç”¨,å¯é€‰ true/false 
geo-update-interval: 48                               # æ›´æ–°é—´éš”,å•ä½å°æ—¶

# è‡ªå®šä¹‰GEOä¸‹è½½åœ°å€ https://github.com/Loyalsoldier/geoip/release
#geox-url:
#  geoip: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.dat"
#  geosite: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geosite.dat"
#  mmdb: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/geoip.metadb"
#  asn: "https://testingcf.jsdelivr.net/gh/MetaCubeX/meta-rules-dat@release/GeoLite2-ASN.mmdb"

# æŒ‡å®šUA
global-client-fingerprint: chrome                     # å…¨å±€å®¢æˆ·ç«¯æŒ‡çº¹
global-ua: "clash.meta"                               # å…¨å±€UA,å¯é€‰"Mozilla/5.0; AppleWebKit/537.36; Chrome/91.0.4472.114; Safari/537.36; Shadowrocket/1.9.7; meta/1.0.0; Sing/1.1.0"

# APIé¢æ¿é…ç½®
external-controller: 0.0.0.0:9090                     # API ç›‘å¬åœ°å€
#external-controller-tls: 0.0.0.0:9443                # HTTPS-APIç›‘å¬åœ°å€,éœ€è¦é…ç½®TLSéƒ¨åˆ†è¯ä¹¦å’Œå…¶ç§é’¥é…ç½®,ä½¿ç”¨TLSä¹Ÿå¿…é¡»å¡«å†™external-controller
# tls:                                                # TLS ç›®å‰ä»…ç”¨äº API çš„ https
  # certificate: "./tls/cert.pem"                     # è¯ä¹¦ PEM æ ¼å¼,æˆ–è€… è¯ä¹¦çš„è·¯å¾„
  # private-key: "./tls/key.pem"                      # è¯ä¹¦å¯¹åº”çš„ç§é’¥ PEM æ ¼å¼,æˆ–è€…ç§é’¥è·¯å¾„
  # custom-certifactes:
    # - "./tls/Mozilla.pem"
external-ui: "./ui"                                   # å¤–éƒ¨é¢æ¿è·¯å¾„
external-ui-name: "1"                                 # å¤–éƒ¨é¢æ¿åç§°/å­è·¯å¾„
external-ui-url: "https://ghp.ci/https://github.com/MetaCubeX/metacubexd/archive/refs/heads/gh-pages.zip"
secret: "888016"                                      # API çš„è®¿é—®å¯†é’¥

# ç­–ç•¥ç¼“å­˜å’Œfakeipç¼“å­˜
profile:
  store-selected: true                                # å‚¨å­˜APIå¯¹ç­–ç•¥ç»„çš„é€‰æ‹©,ä»¥ä¾›ä¸‹æ¬¡å¯åŠ¨æ—¶ä½¿ç”¨
  store-fake-ip: true                                 # fake-ipç¼“å­˜,åŸŸåå†æ¬¡å‘ç”Ÿè¿æ¥æ—¶,ä½¿ç”¨åŸæœ‰æ˜ å°„åœ°å€

# æµé‡å—…æ¢
sniffer:
  enable: true                                        # æ˜¯å¦å¯ç”¨,å¯é€‰ true/false
  force-dns-mapping: true                             # å¯¹ redir-host ç±»å‹è¯†åˆ«çš„æµé‡è¿›è¡Œå¼ºåˆ¶å—…æ¢
  parse-pure-ip: true                                 # å¯¹æ‰€æœ‰æœªè·å–åˆ°åŸŸåçš„æµé‡è¿›è¡Œå¼ºåˆ¶å—…æ¢
  override-destination: true                          # æ˜¯å¦ä½¿ç”¨å—…æ¢ç»“æœä½œä¸ºå®é™…è®¿é—®,é»˜è®¤ä¸º true
  sniff:
    QUIC:
      ports: [443, 8443]
    TLS:                                              # TLS ç«¯å£é…ç½®, å¦‚æœä¸é…ç½® ports é»˜è®¤å—…æ¢ 443
      ports: [443, 8443]
    HTTP:
      ports: [80, 8080-8880]
      override-destination: true                      # å¯è¦†ç›–å…¨å±€override-destination
  force-domain:
    - "+.v2ex.com"
  skip-domain:                                        # éœ€è¦è·³è¿‡å—…æ¢çš„åŸŸå,ä¸»è¦è§£å†³éƒ¨åˆ†ç«™ç‚¹sniå­—æ®µéåŸŸå,å¯¼è‡´å—…æ¢ç»“æœå¼‚å¸¸çš„é—®é¢˜,å¦‚ç±³å®¶è®¾å¤‡
    - "geosite:cn"
    - "Mijia Cloud"
    - "dlg.io.mi.com"
    - "+.push.apple.com"
    - "+.apple.com"

# TUN ä»£ç†æ¨¡å¼é…ç½®
tun:
  enable: true                                        # æ˜¯å¦å¯ç”¨,å¯é€‰ true/false
  stack: system                                       # Tun æ¨¡å¼å †æ ˆ system/gvisor/mixed
  dns-hijack:
    - "any:53"
    - "tcp://any:53"
  auto-detect-interface: true                         # è‡ªåŠ¨è¯†åˆ«å‡ºå£ç½‘å¡
  auto-route: true                                    # é…ç½®è·¯ç”±è¡¨
  auto-redirect: true                                 # è‡ªåŠ¨é…ç½® iptables ä»¥é‡å®šå‘ TCP è¿æ¥
  route-address:                                      # å¯ç”¨ auto-route æ—¶ä½¿ç”¨è‡ªå®šä¹‰è·¯ç”±è€Œä¸æ˜¯é»˜è®¤è·¯ç”±
    - 0.0.0.0/1
    - 128.0.0.0/1
    - "::/1"
    - "8000::/1"

# DNSæ¨¡å—
dns:
  cache-algorithm: arc                                # ç¼“å­˜ç®—æ³•lru/lfu/arc,ä¸€èˆ¬ä¸è®¾ç½®ä½¿ç”¨é»˜è®¤arc
  enable: true                                        # å…³é—­å°†ä½¿ç”¨ç³»ç»Ÿ DNS
  prefer-h3: true                                     # æ˜¯å¦å¼€å¯ DoH æ”¯æŒ HTTP/3ï¼Œå°†å¹¶å‘å°è¯•
  listen: 0.0.0.0:2053                                # å¼€å¯ DNS æœåŠ¡å™¨ç›‘å¬
  ipv6: true                                          # falseå°†è¿”å›AAAAçš„ç©ºç»“æœ
  enhanced-mode: redir-host                           # DNS æ¨¡å¼: redir-host / fake-ip
  fake-ip-range: 28.0.0.0/8                           # fakeip ä¸‹çš„ IP æ®µè®¾ç½® 198.18.0.0/16 28.0.0.1/8
  fake-ip-filter-mode: blacklist                      # fake-ipåŒ¹é…æ¨¡å¼,é»˜è®¤ä¸ºblacklist,å³å¦‚æœåŒ¹é…æˆåŠŸä¸è¿”å›fake-ip,å¯è®¾ç½®ä¸ºwhitelistï¼Œå³åªæœ‰åŒ¹é…æˆåŠŸæ‰è¿”å›fake-ip
  fake-ip-filter:                                     # fakeip è¿‡æ»¤,ä»¥ä¸‹åœ°å€ä¸ä¼šä¸‹å‘ fakeip æ˜ å°„ç”¨äºè¿æ¥
    - "+.lan"
    - "+.invalid.*"
    - "+.local.*"
    - "+.localhost"
    - "+.fzhusheng.*"
    - "+.u160765.us.kg"
    - "geosite:private,cn"
  default-nameserver:                                 # åªç”¨äºè§£æ nameserver ä¸­åŸŸåæ ¼å¼çš„ DNS æœåŠ¡å™¨,å¯ä½¿ç”¨ UDP/DoT/DoH,åªèƒ½ä½¿ç”¨çº¯ IP åœ°å€
    - "tls://223.5.5.5:853"                           # é˜¿é‡ŒDoT
    - "https://120.53.53.53:443/dns-query"            # è…¾è®¯DoH
  nameserver:                                         # é™¤ nameserver-policy æŒ‡å®šè§„åˆ™å¤–çš„æ‰€æœ‰åŸŸåéƒ½ç”± nameserver è§£æ
#    - "192.168.15.201"                                # æœ¬åœ°DNS
    - "tls://dns.google:853"                          # GoogleDNS
    - "https://cloudflare-dns.com:443/dns-query"      # CloudflareDNS
    - "https://doh.opendns.com:443/dns-query"         # OpenDNS
  nameserver-policy:
    "geosite: cn,private":                            # å›½å†…ç½‘å€
      - "tls://dns.alidns.com:853"                    # é˜¿é‡ŒDoT
      - "https://120.53.53.53:443/dns-query"          # è…¾è®¯DoH

# æœºåœºåˆ—è¡¨
p: &p {type: http, health-check: {enable: true, url: "https://www.gstatic.com/generate_204", interval: 120, timeout: 2000, lazy: true}, exclude-filter: "(?i)å›å›½|å®‰å¾½|åŒ—äº¬|é‡åº†|ç¦å»º|ç”˜è‚ƒ|å¹¿ä¸œ|å¹¿è¥¿|è´µå·|æµ·å—|æ²³åŒ—|é»‘é¾™æ±Ÿ|æ²³å—|æ¹–åŒ—|æ¹–å—|å‰æ—|æ±Ÿè‹|æ±Ÿè¥¿|è¾½å®|å†…è’™å¤|å®å¤|é’æµ·|å±±ä¸œ|å±±è¥¿|é™•è¥¿|ä¸Šæµ·|å››å·|å¤©æ´¥|è¥¿è—|æ–°ç–†|äº‘å—|æµ™æ±Ÿ"}
proxy-providers: # ğŸ  â³
  âœˆï¸èšåˆè®¢é˜…: {interval: 86400, url: "https://ghp.ci/https://raw.githubusercontent.com/barry-far/V2ray-Configs/refs/heads/main/Splitted-By-Protocol/ss.txt", override: {skip-cert-verify: true, udp: true, ip-version: ipv6-prefer, additional-prefix: ""}, <<: *p}

# èŠ‚ç‚¹
proxies: 
  - { name: "ğŸŸ¢ ç›´è¿", type: direct, udp: true, hidden: true}
  - { name: "â›” æ‹¦æˆª", type: reject, hidden: true}
  - { name: "â­• DNSåŠ«æŒ", type: dns, hidden: true}

# ä»£ç†ç»„ 
pr: &pr {type: select, proxies: [â™»ï¸ è‡ªåŠ¨æ•…è½¬,ğŸ‡§ BPBèŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ”¶ æ–°æ—¥éŸ©èŠ‚ç‚¹,ğŸ”· æ¸¯å°èŠ‚ç‚¹,ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯èŠ‚ç‚¹,ğŸ”” å…¶ä»–åœ°åŒº,ğŸŸ¢ ç›´è¿]}
url-test: &url-test {type: url-test, interval: 40, tolerance: 70}
proxy-groups:  
  - {name: â™»ï¸ è‡ªåŠ¨æ•…è½¬, type: fallback, proxies: [ğŸ‡§ BPBèŠ‚ç‚¹,ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹,ğŸ”¶ æ–°æ—¥éŸ©èŠ‚ç‚¹,ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯èŠ‚ç‚¹,ğŸ”” å…¶ä»–åœ°åŒº], lazy: true, interval: 20, timeout: 2000, max-failed-times: 2, url: "https://www.gstatic.com/generate_204"} 
  - {name: ğŸ“º è§†é¢‘åª’ä½“, <<: *pr}
  - {name: ğŸ‘½ OpenAI, <<: *pr}
  - {name: â“‚ï¸ MicorSoft, <<: *pr}
  - {name: ğŸ‡¬ Google, <<: *pr}
  - {name: ğŸ Apple, <<: *pr}
  - {name: ğŸ’³ PayPal, <<: *pr}
  - {name: ğŸ“ GitHub, <<: *pr}
  - {name: ğŸ‡µ PornHub, <<: *pr}
  - {name: ğŸ“² Telegram, <<: *pr}
  - {name: ğŸš€ SpeedTest, <<: *pr}
  - {name: ğŸ’  å‡ºå›½ä»£ç†, <<: *pr}
  - {name: ğŸŸ æ¼ç½‘ä¹‹é±¼, <<: *pr}
  - {name: ğŸ“¢ å¹¿å‘Šè¿‡æ»¤, type: select, proxies: [â›” æ‹¦æˆª,ğŸš« ä¸¢å¼ƒ,âšª ç»•è¿‡]}
# åœ°åŒºåˆ†ç»„
  - {name: ğŸ‡§ BPBèŠ‚ç‚¹, <<: *url-test, include-all: true, filter: "(?i)^(?=.*(BPB))((?!(ç›´è¿|DIRECT|æ‹¦æˆª|REJECT|DNSåŠ«æŒ|å…¬ç›Š|æ‰«ç )).)*$"}
  - {name: ğŸ‡ºğŸ‡² ç¾å›½èŠ‚ç‚¹, <<: *url-test, include-all: true, filter: "(?i)^(?=.*(ç¾|US|States|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’å†ˆ|å‡¤å‡°åŸ|è´¹åˆ©è’™|ç¡…è°·|æ‹‰æ–¯ç»´åŠ æ–¯|æ´›æ‰çŸ¶|åœ£ä½•å¡|åœ£å…‹æ‹‰æ‹‰|è¥¿é›…å›¾|èŠåŠ å“¥))((?!(BPB|è‡ªå»º|ç›´è¿|DIRECT|æ‹¦æˆª|REJECT|DNSåŠ«æŒ|ä¸­è½¬|å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"}
  - {name: ğŸ”¶ æ–°æ—¥éŸ©èŠ‚ç‚¹, <<: *url-test, include-all: true, filter: "(?i)^(?=.*(å¡|SG|Singapore|ç‹®åŸ|æ—¥|JP|Japan|éŸ©|KR|Korea))^((?!(è‡ªå»º|ç›´è¿|DIRECT|æ‹¦æˆª|REJECT|DNSåŠ«æŒ|ä¸­è½¬|å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"}
  - {name: ğŸ”· æ¸¯å°èŠ‚ç‚¹, <<: *url-test, include-all: true, filter: "(?i)^(?=.*(æ¸¯|HK|Hong|å°|TW|Taiwan))((?!(US|è‡ªå»º|ç›´è¿|DIRECT|æ‹¦æˆª|REJECT|DNSåŠ«æŒ|ä¸­è½¬|å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"}
  - {name: ğŸ‡·ğŸ‡º ä¿„ç½—æ–¯èŠ‚ç‚¹, <<: *url-test, include-all: true, filter: "(?i)^(?=.*(ä¿„|RU|Russian))((?!(è‡ªå»º|ç›´è¿|DIRECT|æ‹¦æˆª|REJECT|DNSåŠ«æŒ|æ‰«ç |ä¸­è½¬|å®¶å®½|æ¸¸æˆ|å‰©ä½™|æµé‡|0.5|0.5å€|0.5x|2.0|2å€|2x|3.0|3å€|3x|4.0|4å€|4x|5.0|5å€|5x)).)*$"}
  - {name: ğŸ”” å…¶ä»–åœ°åŒº, <<: *url-test, include-all: true, filter: "(?i)^(?!.*(?:ç¾|US|States|æ¸¯|HK|Hong|å°|TW|Taiwan|å¡|SG|Singapore|ç‹®åŸ|æ—¥|JP|Japan|éŸ©|KR|Korea|ä¿„|RU|Russian|è‡ªå»º|ç›´è¿|DIRECT|æ‹¦æˆª|REJECT|DNSåŠ«æŒ)).*$"}
# ç‰¹æ®ŠèŠ‚ç‚¹  
  - {name: ğŸš« ä¸¢å¼ƒ, type: select, proxies: [REJECT-DROP], hidden: true}
  - {name: âšª ç»•è¿‡, type: select, proxies: [PASS], hidden: true}

# åˆ†æµè§„åˆ™
rules:    
#  - AND,((NETWORK,tcp),(DST-PORT,53)),â­• DNSåŠ«æŒ
#  - AND,((NETWORK,udp),(DST-PORT,53)),â­• DNSåŠ«æŒ
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOSITE,cn))),â›” æ‹¦æˆª          # é™¤ä¸­å›½å¤–çš„ QUIC
  - AND,(AND,(DST-PORT,443),(NETWORK,UDP)),(NOT,((GEOIP,CN))),â›” æ‹¦æˆª            # é™¤ä¸­å›½å¤–çš„ QUIC
  - IP-CIDR,127.0.0.1/32,â›” æ‹¦æˆª,no-resolve                                      # ä¿®å¤ DNS æ³„æ¼
  - IP-CIDR6,::1/128,â›” æ‹¦æˆª,no-resolve
  - IP-CIDR,198.18.0.1/16,â›” æ‹¦æˆª,no-resolve
  - IP-CIDR,28.0.0.1/8,â›” æ‹¦æˆª,no-resolve
  - RULE-SET,å°é”åˆ—è¡¨,â›” æ‹¦æˆª
  - GEOSITE,private,ğŸŸ¢ ç›´è¿
  - GEOIP,private,ğŸŸ¢ ç›´è¿,no-resolve
 # å¹¿å‘Šè¿‡æ»¤
  - GEOSITE,category-ads-all,ğŸ“¢ å¹¿å‘Šè¿‡æ»¤
  - RULE-SET,BanAD,ğŸ“¢ å¹¿å‘Šè¿‡æ»¤
  - RULE-SET,BanProgramAD,ğŸ“¢ å¹¿å‘Šè¿‡æ»¤
  - RULE-SET,BanEasyListChina,ğŸ“¢ å¹¿å‘Šè¿‡æ»¤
  - RULE-SET,AWAvenue-Ads,ğŸ“¢ å¹¿å‘Šè¿‡æ»¤
  - RULE-SET,ç›´è¿åˆ—è¡¨,ğŸŸ¢ ç›´è¿
  - RULE-SET,ä»£ç†åˆ—è¡¨,ğŸ’  å‡ºå›½ä»£ç†
 # åˆ†ç±»è§„åˆ™ 
  - RULE-SET,OpenAI,ğŸ‘½ OpenAI
  - RULE-SET,Github,ğŸ“ GitHub
  - RULE-SET,Telegram,ğŸ“² Telegram
  - RULE-SET,Youtube,ğŸ“º è§†é¢‘åª’ä½“
  - RULE-SET,Netflix,ğŸ“º è§†é¢‘åª’ä½“
  - RULE-SET,TikTok,ğŸ“º è§†é¢‘åª’ä½“
  - RULE-SET,PornHub,ğŸ‡µ PornHub
  - RULE-SET,BiliBili,ğŸŸ¢ ç›´è¿
  - RULE-SET,Micorsoft,â“‚ï¸ MicorSoft
  - RULE-SET,Apple,ğŸ Apple
  - RULE-SET,PayPal,ğŸ’³ PayPal
  - RULE-SET,Google,ğŸ‡¬ Google
  - RULE-SET,SpeedTest,ğŸš€ SpeedTest
 # å…œåº•è§„åˆ™
  - GEOSITE,geolocation-!cn,ğŸ’  å‡ºå›½ä»£ç†
  - GEOSITE,category-scholar-!cn,ğŸ’  å‡ºå›½ä»£ç†
  - RULE-SET,GFWåˆ—è¡¨,ğŸ’  å‡ºå›½ä»£ç†
  - GEOSITE,category-games@cn,ğŸŸ¢ ç›´è¿
  - GEOIP,CN,ğŸŸ¢ ç›´è¿,no-resolve
  - GEOSITE,cn,ğŸŸ¢ ç›´è¿
  - MATCH,ğŸŸ æ¼ç½‘ä¹‹é±¼

# è®¢é˜…è§„åˆ™é›†
rule-anchor:
  ip: &ip {behavior: ipcidr, type: http, interval: 86400, format: mrs}
  domain: &domain {behavior: domain, type: http, interval: 86400, format: mrs}
  classic: &classic {behavior: classical, type: http, interval: 86400, format: text}
  yaml: &yaml {behavior: domain, type: http, interval: 86400, format: yaml}
rule-providers: 
  å°é”åˆ—è¡¨: { <<: *classic, url: "https://https://raw.githubusercontent.com/psqtdhx/Config/refs/heads/main/rules-dat/Block.list" }
  ç›´è¿åˆ—è¡¨: { <<: *classic, url: "https://https://raw.githubusercontent.com/psqtdhx/Config/refs/heads/main/rules-dat/Direct.list" }
  ä»£ç†åˆ—è¡¨: { <<: *classic, url: "https://https://raw.githubusercontent.com/psqtdhx/Config/refs/heads/main/rules-dat/Proxy.list" }
  GFWåˆ—è¡¨: { <<: *domain, url: "https://ghp.ci/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/gfw.mrs" }
 # å¹¿å‘Šè¿‡æ»¤
  BanAD: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list" }
  BanProgramAD: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list" }
  BanEasyListChina: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanEasyListChina.list" }
 # ç§‹é£å¹¿å‘Šæ‹¦æˆªè§„åˆ™ https://awavenue.top
  AWAvenue-Ads: { <<: *yaml, url: "https://ghp.ci/https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/refs/heads/main/Filters/AWAvenue-Ads-Rule-Clash.yaml" }
 # OpenAI
  OpenAI: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/OpenAI/OpenAI.list" }
 # æµåª’ä½“
  Youtube: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/YouTube/YouTube.list" }
  Netflix: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Netflix/Netflix.list" }
  TikTok: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/TikTok/TikTok.list" }
  BiliBili: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/BiliBili/BiliBili.list" }
  PornHub: { <<: *domain, url: "https://ghp.ci/https://github.com/MetaCubeX/meta-rules-dat/raw/refs/heads/meta/geo/geosite/category-porn.mrs" }
 # ç”µæŠ¥æ¶ˆæ¯
  Telegram: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Telegram/Telegram.list" }
 # å¾®è½¯æœåŠ¡
  Micorsoft: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Microsoft/Microsoft.list" }
 # è°·æ­ŒæœåŠ¡
  Google: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Google/Google.list" }
 # PayPal
  PayPal: { <<: *domain, url: "https://ghp.ci/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/paypal.mrs"}
 # Apple
  Apple: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Apple/Apple.list" }
 # GitHub
  Github: { <<: *classic, url: "https://ghp.ci/https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/GitHub/GitHub.list" }
 # SpeedTest
  SpeedTest: { <<: *domain, url: "https://ghp.ci/https://raw.githubusercontent.com/MetaCubeX/meta-rules-dat/meta/geo/geosite/ookla-speedtest.mrs"}
